docs(sonarcloud): add first version of sonarcloud documentation
rog-golang-buddies/golang-template-repository pull request #52
Opened 2022-07-11 18:31 UTC by dcristobalh

2022-07-11 22:42 UTC, haani-niyaz commented
@dcristobalh, Seeing as how this is a mandatory step can we also add a step to https://github.com/rog-golang-buddies/golang-template-repository/blob/main/docs/quickstart.md, thanks.

2022-07-11 23:08 UTC, haani-niyaz requested changes

2022-07-11 23:08 UTC, haani-niyaz commented on docs/continuous-integration/sonarcloud.md
> +You can see the results in each PR
Can we include the file in the repo perhaps with the configuration commented out?

2022-07-12 00:35 UTC, haani-niyaz commented on docs/continuous-integration/sonarcloud.md
> +## CI setup
Can we add the workflow location details here? This might sound obvious but for anyone working with Github workflows it can be a useful hint.

Example:
https://rog-golang-buddies.github.io/golang-template-repository/continuous-integration/golangci-lint/

2022-07-13 05:13 UTC, dcristobalh commented on docs/continuous-integration/sonarcloud.md
> +# sonarcloud
Done :rocket:

2022-07-13 05:14 UTC, dcristobalh commented on docs/continuous-integration/sonarcloud.md
> +A `.sonar-project.properties` file is required when you add a project in sonarcloud web ui with this two values:
Sorry, done as well

2022-07-13 05:17 UTC, dcristobalh commented on docs/continuous-integration/sonarcloud.md
> +    PO will need to add a github token and a sonarcloud token in github secrets, the last one is provided when register your repository in sonarcloud.
> Does the PO need to explicitly add a Github token? I'm asking since I don't see this in our repo: ![Screen Shot 2022-07-12 at 8 56 43 am](https://user-images.githubusercontent.com/5335941/178372628-7a09a934-9aab-485d-a583-bdde7231a55b.png)
> 
> The workflow leverages the [GITHUB_TOKEN secret](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret).

AFAIK you need GITHUB token when you want the results in a comment inside the PR

2022-07-14 03:26 UTC, haani-niyaz commented
hey @shukra-in-spirit, happen to see the org level `SONAR_TOKEN` variable, is this ready for use?

@dcristobalh just a heads up: If this token is ready, it means we no longer need the docs on setting up the the token. It takes care of running the workflow but we still have to deal with `sonar.projectKey` property:

```
sonar.projectKey=rog-golang-buddies_golang-template-repository
```

Given that this is required for the scans to run successfully in the template repo, it means when cloned/forked, unless users change the `sonar.projectKey` it will override the project (happy to be corrected). My gut feeling is that some users will ignore setup instructions so we need to handle this scenario. One way to fix this would be to move it into a repo variable that users will have to set as part of the initial onboarding.

Example:

```
- name: Analyze with SonarCloud
  uses: sonarsource/sonarcloud-github-action@master
  with:
    projectBaseDir: my-custom-directory
    args: >
      -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY}}
```

`SONAR_PROJECT_KEY` would be set within the repo secrets (_Don't know much about Github actions but it doesn't look like you can set a custom env variable anywhere so I'm using a secret here_)

If users clone/fork and run without setting this variable it should fail. Atleast this way there is a call to action.

2022-07-14 04:53 UTC, shukra-in-spirit commented
Hey, @haani-niyaz @dcristobalh I had added the token yesterday and completeley forgot to mention it om discord. I have not tested it yet, though. I have shared the secret with apl public repositories in the org. Can you guys check once if everything is working?

2022-07-14 22:59 UTC, haani-niyaz commented
> Hey, @haani-niyaz @dcristobalh I had added the token yesterday and completeley forgot to mention it om discord. I have not tested it yet, though. I have shared the secret with apl public repositories in the org. Can you guys check once if everything is working?

Re-ran the failed job from here and it worked:
https://github.com/rog-golang-buddies/recipe_suggester/actions/runs/2652699507

Also an example of how it is targeting the wrong SonarCloud project:

```
INFO: ANALYSIS SUCCESSFUL, you can find the results at: https://sonarcloud.io/dashboard?id=rog-golang-buddies_golang-template-repository
```
Ref: https://github.com/rog-golang-buddies/recipe_suggester/runs/7349350424?check_suite_focus=true#step:4:155

2022-07-16 05:50 UTC, dcristobalh commented
> hey @shukra-in-spirit, happen to see the org level `SONAR_TOKEN` variable, is this ready for use?
> 
> @dcristobalh just a heads up: If this token is ready, it means we no longer need the docs on setting up the token. It takes care of running the workflow but we still have to deal with `sonar.projectKey` property:
> 
> ```
> sonar.projectKey=rog-golang-buddies_golang-template-repository
> ```
> 
> Given that this is required for the scans to run successfully in the template repo, it means when cloned/forked, unless users change the `sonar.projectKey` it will override the project (happy to be corrected). My gut feeling is that some users will ignore setup instructions so we need to handle this scenario. One way to fix this would be to move it into a repo variable that users will have to set as part of the initial onboarding.
> 
> Example:
> 
> ```
> - name: Analyze with SonarCloud
>   uses: sonarsource/sonarcloud-github-action@master
>   with:
>     projectBaseDir: my-custom-directory
>     args: >
>       -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY}}
> ```
> 
> `SONAR_PROJECT_KEY` would be set within the repo secrets (_Don't know much about Github actions but it doesn't look like you can set a custom env variable anywhere so I'm using a secret here_)
> 
> If users clone/fork and run without setting this variable it should fail. Atleast this way there is a call to action.

Hey @haani-niyaz @shukra-in-spirit I have added new step in sonarcloud workflow for checking if the variable is set correctly

2022-07-16 22:27 UTC, haani-niyaz commented on .github/workflows/sonarcloud.yml
> +          fi
@dcristobalh, looks like this implementation expects the user to add the `SONAR_PROJECT_KEY ` secret but also set the value in the `sonar-project.properties` which IMO is not required when we can pass the `SONAR_PROJECT_KEY` as an argument as per my previous [comment](https://github.com/rog-golang-buddies/golang-template-repository/pull/52#issuecomment-1183941757)?

2022-07-16 22:58 UTC, haani-niyaz commented on docs/quickstart.md
> +
@dcristobalh I should have added some context about what goes into this section. 

The Quickstart is meant to capture "at a glance" setup instructions, so anything we need to bring to their attention to get things working. In this case the following will do:

```
### Setup project key for [SonarCloud](continuous-integration/sonarcloud.md)

Add `SONAR_PROJECT_KEY` as a Github secret. This is the value you you typically set for `sonar.projectKey` property in the `sonar-project.properties` file.

2022-07-17 09:42 UTC, dcristobalh commented on .github/workflows/sonarcloud.yml
> +          fi
Yep sorry, then the file sonar-project.properties is useless because you can add organization argument as you said with sonar project key. I guess organization argument is always the same, please check it out and let me know if I have to change anything

2022-07-19 09:47 UTC, haani-niyaz commented on docs/quickstart.md
> +### Setup project key for [SonarCloud](continuous-integration/sonarcloud.md)
@dcristobalh a copy edit to keep the language similar to the other docs:

```
### Setup project key for [SonarCloud](continuous-integration/sonarcloud.md)

Add `SONAR_PROJECT_KEY` as a Github secret as per the [CI setup](continuous-integration/sonarcloud.md#ci-setup) instructions. This is the value you typically set for `sonar.projectKey` property in the `sonar-project.properties` file.
```

2022-07-19 09:47 UTC, haani-niyaz commented on docs/continuous-integration/sonarcloud.md
> +## How
@dcristobalh I'm going to suggest we replace this section with:

```
## How

SonarCloud decorates your pull requests, giving you feedback such as a barometer on the quality of your PR and a quality gate indicator.
```

We can keep the image as-is.

2022-07-19 09:47 UTC, haani-niyaz commented on docs/continuous-integration/sonarcloud.md
> +## CI setup
@dcristobalh, I had a look at the docs and it looks like we don't need to set a token as per https://github.com/SonarSource/sonarcloud-github-action#secrets: 

> GITHUB_TOKEN – Provided by Github

If you then look at the `GITHUB_TOKEN` docs:

> At the start of each workflow run, GitHub automatically creates a unique GITHUB_TOKEN secret to use in your workflow. You can use the GITHUB_TOKEN to authenticate in a workflow run.

Based on this I suggest we update the docs (_I've also made some edits to keep it similar to the other docs_):

```
## CI setup

SonarCloud analysis is executed via the `sonarcloud` Github workflow in `.github/workflows/sonarcloud.yml`.

!!! summary

    A repository owner will need to set a `SONAR_PROJECT_KEY` Github secret variable.

Every repository will require a unique [project key](https://docs.sonarcloud.io/advanced-setup/analysis-parameters/). This must be configured as a Github secret variable in your repository settings. The variable name must be set to `SONAR_PROJECT_KEY`.

![gh-secrets](img/gh-secrets.png)

!!! tip

    The `SONAR_TOKEN` Github secret is set at the organizational level and is available for reuse in your repository.
```

2022-07-19 09:49 UTC, haani-niyaz commented
@dcristobalh I've left some review comments. I took the liberty of making some edits. Call out if you have any concerns/questions, thanks!

2022-07-29 05:51 UTC, dcristobalh commented
It is decided not to include sonarcloud

2022-07-29 05:51 UTC, closed without merging